const Qomparison = "Qomparison",
  dataPathMap = "dataPathObjectMap",
  aDataPathLbl = "label",
  paramName = "parameter",
  isMandatory = "required",
  cigInvolved = "cigInvolved",
  actionList = "actions",
  pathList = "dataPaths",
  outputArray = "constraints",
  typePath = "typeOf",
  xpath = "Jpath",
  defaultVal = "defaultVal",
  action = "action",
  details = "details",
  arg1 = "arg1",
  arg2 = "arg2",
  functLabel = "function",
  symbol = "symbol",
  rhsArg = "rhsArg",
  lhsArg = "lhsArg",
  outcome = "output",
  comparison = "comparison",
  //compare = "compare",
  findRef = "findRef",
  argList = "actionsRef",
  queryArgs = "actionsRef",
  //parameters
  medsGenParam = "medications_general",
  medsSelectParam = "medications_user_selection",
  //labels to find templates on MongoDb
  dss = "dss-template",
  ehr = "ehr-template",
  tmr = "tmr-template",
  labelTemplate = "label",
  bodyTemplate = "body",
  addTemplate = "add",
  fields = "fields",
  aPath = "path",
  entryField = "entryObject_property",
  entryTemplate = "entryObject",
  patientId = "patientId",
  //result object fields
  datalist = "data",
  ciglist = "cigList",
  isAOrEq = "isAOrEq",
  hasAOrEq = "hasAOrEq",
  isSubsetOf = "isSubsetOf",
  isSupersetOf = "isSupersetOf",
  includes = "includes",
  isIncluded = "isIncluded",
  In = "in",
  contains = "contains",
  subsumes = "subsumes",
  isA = "isA",
  hasA = "hasA",
  parentOf = "parentOf",
  parentOrSelfOf = "parentOrSelfOf",
  childOf = "childOf",
  childOrSelfOf = "childOrSelfOf",
  descendantOrSelfOf = "descendantOrSelfOf",
  descendantOf = "descendantOrSelfOf",
  ancestorOrSelfOf = "ancestorOrSelfOf",
  ancestorOf = "ancestorOf",
  codeSys = "codeSystem",
  termSys = "termSystem",
  count = "count",
  filterTerm = "filter",
  noCIG = "non-cig",
  anyElemIn = "anyElemIn",
  filterByClass = "filterByClass",
  subsumesOrEq = "subsumesOrEq",
  pipeline_id = 'pipeline_id',
  service_id_list = 'service_id_list';
export {
  pipeline_id,
  service_id_list,
  Qomparison,
  dataPathMap,
  noCIG,
  paramName,
  isMandatory,
  cigInvolved,
  actionList,
  pathList,
  outputArray,
  typePath,
  xpath,
  defaultVal,
  action,
  details,
  arg1,
  arg2,
  functLabel,
  symbol,
  rhsArg,
  lhsArg,
  outcome,
  comparison,
  //compare,
  findRef,
  argList,
  queryArgs,
  //parameters
  medsGenParam,
  medsSelectParam,
  //labels to find templates on MongoDb
  dss,
  ehr,
  tmr,
  labelTemplate,
  bodyTemplate,
  addTemplate,
  fields,
  aPath,
  entryField,
  entryTemplate,
  patientId,
  //result object fields
  datalist,
  ciglist,
  isA,
  hasA,
  isAOrEq,
  hasAOrEq,
  isSubsetOf,
  isSupersetOf,
  includes,
  isIncluded,
  In,
  contains,
  subsumes,
  anyElemIn,
  filterByClass,
  subsumesOrEq,
  parentOf,
  parentOrSelfOf,
  childOf,
  childOrSelfOf,
  descendantOrSelfOf,
  descendantOf,
  ancestorOrSelfOf,
  ancestorOf,
  codeSys,
  aDataPathLbl,
  termSys,
  count,
  filterTerm
};
