module.exports = {
   paramName : "parameter",
isMandatory : "required",
cigInvolved : "cigInvolved",
actionList :"actionList",
pathList :"pathList",
 resultList : "resultList",
typePath : "typeOf",
xpath : "Jpath",
defaultVal : "defaultVal",
 action : "action",
details : "details",
 pathListIndex : "pathListIndex",
 functName : "function_name",
 functLabel : "function",
 resultArgListIndex : "resultArgListIndex",
outcome : "outcome",
comparison : "comparison",
compare : "compare",
findRef : "findRef",
argList : "argList",
//parameters
 medsGenParam : 'medications_general', medsSelectParam : 'medications_user_selection',
 //labels to find templates on MongoDb
dss: "dss-template",
ehr: "ehr-template",
tmr: "tmr-template",
labelTemplate: "label",
bodyTemplate: "body",
addTemplate: "add",
fields: "fields",
aPath: "path",
entryField: "entryObject_property",
entryTemplate: "entryObject",
patientId: "patientId",
//result object fields
datalist: 'dataList',
ciglist: 'cigList',
isAncestor_strict: "isAncestor-strict",
isAncestor_eq: "isAncestor-eq",
codeSyst: "codeSystemId"
}