const Qomparison= "Qomparison",
 dataPathMap = "dataPathObjectMap",
    aDataPathLbl = "label",
    paramName= "parameter",
    isMandatory= "required",
    cigInvolved= "cigInvolved",
    actionList= "actions",
    pathList= "dataPaths",
    outcomeList= "output",
    typePath= "typeOf",
    xpath= "Jpath",
    defaultVal= "defaultVal",
    action= "action",
    details= "details",
    arg1= "arg1",
    arg2= "arg2",
    functLabel= "function",
    symbol= "symbol",
    rhsArg= "rhsArg",
    lhsArg= "lhsArg",
    outcome= "outcome",
    comparison= "comparison",
    //compare = "compare",
    findRef= "findRef",
    argList= "queryArgs",
    queryArgs= "queryArgs",
    //parameters
    medsGenParam= 'medications_general',
    medsSelectParam= 'medications_user_selection',
    //labels to find templates on MongoDb
    dss= "dss-template",
    ehr= "ehr-template",
    tmr= "tmr-template",
    labelTemplate= "label",
    bodyTemplate= "body",
    addTemplate= "add",
    fields= "fields",
    aPath= "path",
    entryField= "entryObject_property",
    entryTemplate= "entryObject",
    patientId= "patientId",
    //result object fields
    datalist= 'data',
    ciglist= 'cigList',
    isAncestor_eq= "subClassOf",
    codeSyst= "codeSystemId",
    noCIG="non-cig";
    export  {
        Qomparison,
        dataPathMap,
        noCIG,
        paramName,
        isMandatory,
        cigInvolved,
        actionList,
        pathList,
        outcomeList,
        typePath,
        xpath,
        defaultVal,
        action,
        details,
        arg1,
        arg2,
        functLabel,
        symbol,
        rhsArg,
        lhsArg,
        outcome,
        comparison,
        //compare,
        findRef,
        argList,
        queryArgs,
        //parameters
        medsGenParam,
        medsSelectParam,
        //labels to find templates on MongoDb
        dss,
        ehr,
        tmr,
        labelTemplate,
        bodyTemplate,
        addTemplate,
        fields,
        aPath,
        entryField,
        entryTemplate,
        patientId,
        //result object fields
        datalist,
        ciglist,
        isAncestor_eq,
        codeSyst,
        aDataPathLbl
    };