module.exports = {
paramName : "parameter",
isMandatory : "required",
cigInvolved : "cigInvolved",
actionList : "actions",
pathList :"dataPaths",
outcomeList : "output",
typePath : "typeOf",
xpath : "Jpath",
defaultVal : "defaultVal",
action : "action",
details : "details",
arg1 : "arg1",
arg2 : "arg2",
 functLabel : "function",
 symbol: "symbol",
 rhsArg : "rhsArg",
 lhsArg : "lhsArg",
outcome : "outcome",
comparison : "comparison",
Qomparison : "Qomparison",
//compare : "compare",
findRef : "findRef",
argList : "queryArgs",
queryArgs : "queryArgs",
//parameters
 medsGenParam : 'medications_general',
medsSelectParam : 'medications_user_selection',
 //labels to find templates on MongoDb
dss: "dss-template",
ehr: "ehr-template",
tmr: "tmr-template",
labelTemplate: "label",
bodyTemplate: "body",
addTemplate: "add",
fields: "fields",
aPath: "path",
entryField: "entryObject_property",
entryTemplate: "entryObject",
patientId: "patientId",
//result object fields
datalist: 'data',
ciglist: 'cigList',
isAncestor_eq: "subClassOf",
codeSyst: "codeSystemId"
}